### ISSUE TITLE
Integration of react-toolkit-all with Vite.js

### ISSUE THREAD

**Issue by GHEMID-Mohamed** [AxaFrance/react-toolkit#1190]
### Issue and Steps to Reproduce

Install `react-toolkit-all` package : 

`npm install @axa-fr/react-toolkit-all --save`

Run : `npm run start` on a project initiated with `Vite.js`

Bug : Vite can't load scss files from `react-toolkit-all` package ( export problem )

#### Versions
Vite.js : **5.1.6**
react-toolkit-all : **2.3.1**

#### Screenshots
![image](https://github.com/AxaFrance/react-toolkit/assets/25125613/9b45b08a-e400-425f-8457-3464656093d8)

#### Expected
Loading this package as normal as possible !

**Comment by MartinWeb** [comment]
@GHEMID-Mohamed did you install bootstrap in the 4.3.1 exact version on your project ? 
After did you import the bootstrap css file that we need in the project ? 

`import 'bootstrap/scss/bootstrap-grid.scss';
import 'bootstrap/scss/bootstrap-reboot.scss';`

**Comment by GHEMID-Mohamed** [comment]
Thank you @MartinWeb, but even when I added the imports, I've always the same problem : 

```bash
Error: Missing "./src/bootstrap/theme.scss" specifier in "@axa-fr/react-toolkit-core" package
    at e (file:///C:/Users/B292HI/axa-projects/vite-project/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:48769:25)
    at n (file:///C:/Users/B292HI/axa-projects/vite-project/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:48769:627)
    at o (file:///C:/Users/B292HI/axa-projects/vite-project/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:48769:1297)
    at resolveExportsOrImports (file:///C:/Users/B292HI/axa-projects/vite-project/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:49459:20)
    at resolveDeepImport (file:///C:/Users/B292HI/axa-projects/vite-project/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:49478:31)
    at tryNodeResolve (file:///C:/Users/B292HI/axa-projects/vite-project/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:49203:20)
    at Context.resolveId (file:///C:/Users/B292HI/axa-projects/vite-project/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:48953:28)
    at Object.resolveId (file:///C:/Users/B292HI/axa-projects/vite-project/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:52236:64)
    at async Object.<anonymous> (file:///C:/Users/B292HI/axa-projects/vite-project/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:69516:21)
    at async internalImporter (file:///C:/Users/B292HI/axa-projects/vite-project/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:32799:26)
```

Here's a repository that reproduces the bug : https://github.com/GHEMID-Mohamed/react-toolkit-vite-bug ( node.js 20 is required )

After doing some investigations, the problem comes from the configuration of exporting modules in React-Toolkit Core that does not include exporting scss modules !

in `packages\core\package.json`, adding this configuration may solve the problem : 

```json
  "exports": {
    ".": {
      ...
    "./src/*.scss": {
      "import": "./src/*.scss",
      "require": "./src/*.scss"
    }
  },
```
I'll test it and will create a Pull Request if it works !

NB: Everything works fine when I install react-toolkit components independantly, the problem occurs only when I install the package : `@axa-fr/react-toolkit-all`
